# CARGA PAQUETES PARA DEPURAR BBDD Y FUNCIONES AUXILIARES

pkgs2use<- c('tidyverse','readxl')

inst.load.pkg <- function(pkg){ 
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}


invisible(lapply(pkgs2use,inst.load.pkg))
rm(pkgs2use,inst.load.pkg)

factor.ordinal <- function(x){
  x <- factor(x,levels=c("Pas du tout d'accord","Pas d'accord",
                         "Plutôt pas d'accord","Plutôt d'accord",
                         "D'accord","Tout à fait d'accord"),ordered=TRUE)
  as.numeric(x)
}


# DEPURACIÓN BASE DE DATOS NETFLIX 2020: RECODIFICACIÓN

datos <- readxl::read_xlsx('Netflix2020.xlsx')

colnames(datos) <- c('ID','Plataformas','OtrasPlataformas','FrecuenciaInternet',
                     'SeriesFavoritas','OtrasSeriesFavoritas','FrecuenciaNetflix',
                     'RecenciaNetflix','IntencionNetflix1',paste0('BenefEsp',1:13),
                     paste0('Actitud',1:3),paste0('Barreras',1:9),'ControlPerc1',
                     paste0('NormaDescriptiva',1:2),paste0('NormaSubjetiva',1:2),
                     'IntencionNetflix2','ControlPerc2','Sexo','OtroSexo',
                     'Edad','Comentario','TiempoResp')

datos$Plataformas <- forcats::fct_recode(datos$Plataformas,
                                         'Otras'='autre (précisez)',
                                         'Netflix'='Netflix',
                                         'Netflix;Amazon Prime Video'='Netflix;Amazone prime vidéo',
                                         'Netflix;Apple TV+;Amazon Prime Video'='Netflix;Apple TV+;Amazone prime vidéo',
                                         'Netflix;Apple TV+;Otras'='Netflix;Apple TV+;autre (précisez)',
                                         'Netflix;Apple TV+;Disney+'='Netflix;Apple TV+;disney+',
                                         'Netflix;Otras'='Netflix;autre (précisez)',
                                         'Netflix;Canal+ serie y/o film'='Netflix;Canal+ série et/ou film',
                                         'Netflix;Canal+ serie y/o film;Amazon Prime Video'='Netflix;Canal+ série et/ou film;Amazone prime vidéo',
                                         'Netflix;Canal+ serie y/o film;Amazon Prime Video;Disney+'='Netflix;Canal+ série et/ou film;Amazone prime vidéo;disney+',
                                         'Netflix;Canal+ serie y/o film;Amazon Prime Video;Disney+;Otras'='Netflix;Canal+ série et/ou film;Amazone prime vidéo;disney+;autre (précisez)',
                                         'Netflix;Canal+ serie y/o film;Apple TV+'='Netflix;Canal+ série et/ou film;Apple TV+',
                                         'Netflix;Canal+ serie y/o film;Apple TV+;Amazon Prime Video'='Netflix;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo',
                                         'Netflix;Canal+ serie y/o film;Apple TV+;Amazon Prime Video;Otras'='Netflix;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo;autre (précisez)',
                                         'Netflix;Canal+ serie y/o film;Apple TV+;Amazon Prime Video;Disney+'='Netflix;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo;disney+',
                                         'Netflix;Canal+ serie y/o film;Apple TV+;Amazon Prime Video;Disney+;Otras'='Netflix;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo;disney+;autre (précisez)',
                                         'Netflix;Canal+ serie y/o film;Apple TV+;Disney+'='Netflix;Canal+ série et/ou film;Apple TV+;disney+',
                                         'Netflix;Canal+ serie y/o film;Otras'='Netflix;Canal+ série et/ou film;autre (précisez)',
                                         'Netflix;Canal+ serie y/o film;Disney+'='Netflix;Canal+ série et/ou film;disney+',
                                         'Netflix;OCS'='Netflix;OCS',
                                         'Netflix;OCS;Amazon Prime Video'='Netflix;OCS;Amazone prime vidéo',
                                         'Netflix;OCS;Amazon Prime Video;Disney+'='Netflix;OCS;Amazone prime vidéo;disney+',
                                         'Netflix;OCS;Apple TV+;Amazon Prime Video'='Netflix;OCS;Apple TV+;Amazone prime vidéo',
                                         'Netflix;OCS;Canal+ serie y/o film'='Netflix;OCS;Canal+ série et/ou film',
                                         'Netflix;OCS;Canal+ serie y/o film;Amazon Prime Video'='Netflix;OCS;Canal+ série et/ou film;Amazone prime vidéo',
                                         'Netflix;OCS;Canal+ serie y/o film;Amazon Prime Video;Disney+'='Netflix;OCS;Canal+ série et/ou film;Amazone prime vidéo;disney+',
                                         'Netflix;OCS;Canal+ serie y/o film;Amazon Prime Video;Disney+;Otras'='Netflix;OCS;Canal+ série et/ou film;Amazone prime vidéo;disney+;autre (précisez)',
                                         'Netflix;OCS;Canal+ serie y/o film;Apple TV+'='Netflix;OCS;Canal+ série et/ou film;Apple TV+',
                                         'Netflix;OCS;Canal+ serie y/o film;Apple TV+;Amazon Prime Video'='Netflix;OCS;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo',
                                         'Netflix;OCS;Canal+ serie y/o film;Apple TV+;Amazon Prime Video;Otras'='Netflix;OCS;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo;autre (précisez)',
                                         'Netflix;OCS;Canal+ serie y/o film;Apple TV+;Amazon prime video;Disney+'='Netflix;OCS;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo;disney+',
                                         'Netflix;OCS;Canal+ serie y/o film;Apple TV+;Amazon prime video;Disney+;Otra'='Netflix;OCS;Canal+ série et/ou film;Apple TV+;Amazone prime vidéo;disney+;autre (précisez)',
                                         'Netflix;OCS;Canal+ serie y/o film;Disney+'='Netflix;OCS;Canal+ série et/ou film;disney+',
                                         'Netflix;OCS;Disney+'='Netflix;OCS;disney+')


datos$FrecuenciaInternet <- factor(forcats::fct_recode(datos$FrecuenciaInternet,
                                                       '7 o más horas'='7 heures et +',
                                                       'Entre 0 y 30 minutos'='Entre 0 et 30 minutes',
                                                       'Entre 1 y 2 horas'='Entre 1 et 2 heures',
                                                       'Entre 2 y 3 horas'='Entre 2 et 3 heures',
                                                       'Entre 3 y 5 horas'='Entre 3 et 5 heures',
                                                       'Entre 30 minutos y 1 hora'='Entre 30 minutes et 1 heure',
                                                       'Entre 5 y 7 horas'='Entre 5 et 7 heures'),levels=
                                     c('Entre 0 y 30 minutos','Entre 30 minutos y 1 hora','Entre 1 y 2 horas',
                                       'Entre 2 y 3 horas','Entre 3 y 5 horas','Entre 5 y 7 horas','7 o más horas'),ordered=TRUE)


datos$SeriesFavoritas <- forcats::fct_recode(datos$SeriesFavoritas,
                                             'Anime'='animé',
                                             'Aventura/Accion'='aventure/action',
                                             'Aventura/Accion;Biopic'='aventure/action;biopic (biographie)',
                                             'Aventura/Accion;Documental;Anime'='aventure/action;documentaire;animé',
                                             'Aventura/Accion;Documental;Drama'='aventure/action;documentaire;drame',
                                             'Aventura/Accion;Documental;Thriller'='aventure/action;documentaire;thriller',
                                             'Aventura/Accion;Drama;Infantil'='aventure/action;drame;jeunesse et famille',
                                             'Aventura/Accion;Drama;Romantica'='aventure/action;drame;romantique',
                                             'Aventura/Accion;Drama;Thriller'='aventure/action;drame;thriller',
                                             'Aventura/Accion;Historica;Anime'='aventure/action;historique;animé',
                                             'Aventura/Accion;Historica;Biopic'='aventure/action;historique;biopic (biographie)',
                                             'Aventura/Accion;Historica;Drama'='aventure/action;historique;drame',
                                             'Aventura/Accion;Historica;Romantica'='aventure/action;historique;romantique',
                                             'Aventura/Accion;Historica;Thriller'='aventure/action;historique;thriller',
                                             'Aventura/Accion;Thriller'='aventure/action;thriller',
                                             'Aventura/Accion;Thriller;Romantica'='aventure/action;thriller;romantique',
                                             'Biopic'='biopic (biographie)',
                                             'Documental;Anime;Biopic'='documentaire;animé;biopic (biographie)',
                                             'Documental;Anime;Romantica'='documentaire;animé;romantique',
                                             'Documental;Drama;Biopic'='documentaire;drame;biopic (biographie)',
                                             'Documental;Drama;Romantica'='documentaire;drame;romantique',
                                             'Drama;Biopic;Romantica'='drame;biopic (biographie);romantique',
                                             'Drama;Romantica'='drame;romantique',
                                             'Drama;Thriller'='drame;thriller',
                                             'Drama;Thriller;Anime'='drame;thriller;animé',
                                             'Drama;Thriller;Infantil'='drame;thriller;jeunesse et famille',
                                             'Historica;Drama;Romantica'='historique;drame;romantique',
                                             'Historica;Thriller'='historique;thriller',
                                             'Terror'='horreur',
                                             'Terror;Aventura/Accion;Anime'='horreur;aventure/action;animé',
                                             'Terror;Aventura/Accion;Documental'='horreur;aventure/action;documentaire',
                                             'Terror;Aventura/Accion;Drama'='horreur;aventure/action;drame',
                                             'Terror;Aventura/Accion;Historica'='horreur;aventure/action;historique',
                                             'Terror;Aventura/Accion;Infantil'='horreur;aventure/action;jeunesse et famille',
                                             'Terror;Aventura/Accion;Thriller'='horreur;aventure/action;thriller',
                                             'Terror;Documental;Drama'='horreur;documentaire;drame',
                                             'Terror;Drama;Romantica'='horreur;drame;romantique',
                                             'Terror;Drama;Thriller'='horreur;drame;thriller',
                                             'Terror;Infantil;Romantica'='horreur;jeunesse et famille;romantique',
                                             'Terror;Thriller;Anime'='horreur;thriller;animé',
                                             'Humor/Comedia'='humour/comédie',
                                             'Humor/Comedia;Anime;Otra'='humour/comédie;animé;autre (précisez)',
                                             'Humor/Comedia;Anime;Infantil'='humour/comédie;animé;jeunesse et famille',
                                             'Humor/Comedia;Anime;Romantica'='humour/comédie;animé;romantique',
                                             'Humor/Comedia;Aventura/Accion'='humour/comédie;aventure/action',
                                             'Humor/Comedia;Aventura/Accion;Anime'='humour/comédie;aventure/action;animé',
                                             'Humor/Comedia;Aventura/Accion;Documental'='humour/comédie;aventure/action;documentaire',
                                             'Humor/Comedia;Aventura/Accion;Drama'='humour/comédie;aventure/action;drame',
                                             'Humor/Comedia;Aventura/Accion;Historica'='humour/comédie;aventure/action;historique',
                                             'Humor/Comedia;Aventura/Accion;Infantil'='humour/comédie;aventure/action;jeunesse et famille',
                                             'Humor/Comedia;Aventura/Accion;Romantica'='humour/comédie;aventure/action;romantique',
                                             'Humor/Comedia;Aventura/Accion;Thriller'='humour/comédie;aventure/action;thriller',
                                             'Humor/Comedia;Biopic;Romantica'='humour/comédie;biopic (biographie);romantique',
                                             'Humor/Comedia;Documental;Anime'='humour/comédie;documentaire;animé',
                                             'Humor/Comedia;Documental;Infantil'='humour/comédie;documentaire;jeunesse et famille',
                                             'Humor/Comedia;Documental;Romantica'='humour/comédie;documentaire;romantique',
                                             'Humor/Comedia;Drama;Romantica'='humour/comédie;drame;romantique',
                                             'Humor/Comedia;Drama;Thriller'='humour/comédie;drame;thriller',
                                             'Humor/Comedia;Historica;Biopic'='humour/comédie;historique;biopic (biographie)',
                                             'Humor/Comedia;Historica;Drama'='humour/comédie;historique;drame',
                                             'Humor/Comedia;Historica;Infantil'='humour/comédie;historique;jeunesse et famille',
                                             'Humor/Comedia;Historica;Thriller'='humour/comédie;historique;thriller',
                                             'Humor/Comedia;Terror;Anime'='humour/comédie;horreur;animé',
                                             'Humor/Comedia;Terror;Aventura/Accion'='humour/comédie;horreur;aventure/action',
                                             'Humor/Comedia;Terror;Documental'='humour/comédie;horreur;documentaire',
                                             'Humor/Comedia;Terror;Infantil'='humour/comédie;horreur;jeunesse et famille',
                                             'Humor/Comedia;Terror;Romantica'='humour/comédie;horreur;romantique',
                                             'Humor/Comedia;Terror;Thriller'='humour/comédie;horreur;thriller',
                                             'Humor/Comedia;Infantil;Romantica'='humour/comédie;jeunesse et famille;romantique',
                                             'Humor/Comedia;Monologos;Anime'='humour/comédie;stand-up;animé',
                                             'Humor/Comedia;Monologos;Aventura/Accion'='humour/comédie;stand-up;aventure/action',
                                             'Humor/Comedia;Monologos;Documental'='humour/comédie;stand-up;documentaire',
                                             'Humor/Comedia;Monologos;Thriller'='humour/comédie;stand-up;thriller',
                                             'Humor/Comedia;Thriller;Biopic'='humour/comédie;thriller;biopic (biographie)',
                                             'Romantica'='romantique',
                                             'Ciencia Ficcion'='Science Fiction',
                                             'Ciencia Ficcion;Aventura/Accion'='Science Fiction;aventure/action',
                                             'Ciencia Ficcion;Aventura/Accion;Anime'='Science Fiction;aventure/action;animé',
                                             'Ciencia Ficcion;Aventura/Accion;Documental'='Science Fiction;aventure/action;documentaire',
                                             'Ciencia Ficcion;Aventura/Accion;Drama'='Science Fiction;aventure/action;drame',
                                             'Ciencia Ficcion;Aventura/Accion;Romantica'='Science Fiction;aventure/action;romantique',
                                             'Ciencia Ficcion;Aventura/Accion;Thriller'='Science Fiction;aventure/action;thriller',
                                             'Ciencia Ficcion;Biopic;Infantil'='Science Fiction;biopic (biographie);jeunesse et famille',
                                             'Ciencia Ficcion;Documental;Anime'='Science Fiction;documentaire;animé',
                                             'Ciencia Ficcion;Drama;Thriller'='Science Fiction;drame;thriller',
                                             'Ciencia Ficcion;Historica;Thriller'='Science Fiction;historique;thriller',
                                             'Ciencia Ficcion;Terror'='Science Fiction;horreur',
                                             'Ciencia Ficcion;Terror;Anime'='Science Fiction;horreur;animé',
                                             'Ciencia Ficcion;Terror;Aventura/Accion'='Science Fiction;horreur;aventure/action',
                                             'Ciencia Ficcion;Terror;Documental'='Science Fiction;horreur;documentaire',
                                             'Ciencia Ficcion;Terror;Romantica'='Science Fiction;horreur;romantique',
                                             'Ciencia Ficcion;Terror;Thriller'='Science Fiction;horreur;thriller',
                                             'Ciencia Ficcion;Humor/Comedia'='Science Fiction;humour/comédie',
                                             'Ciencia Ficcion;Humor/Comedia;Anime'='Science Fiction;humour/comédie;animé',
                                             'Ciencia Ficcion;Humor/Comedia;Aventura/Accion'='Science Fiction;humour/comédie;aventure/action',
                                             'Ciencia Ficcion;Humor/Comedia;Documental'='Science Fiction;humour/comédie;documentaire',
                                             'Ciencia Ficcion;Humor/Comedia;Historica'='Science Fiction;humour/comédie;historique',
                                             'Ciencia Ficcion;Humor/Comedia;Terror'='Science Fiction;humour/comédie;horreur',
                                             'Ciencia Ficcion;Humor/Comedia;Romantica'='Science Fiction;humour/comédie;romantique',
                                             'Ciencia Ficcion;Humor/Comedia;Monologos'='Science Fiction;humour/comédie;stand-up',
                                             'Ciencia Ficcion;Humor/Comedia;Thriller'='Science Fiction;humour/comédie;thriller',
                                             'Ciencia Ficcion;Thriller;Anime'='Science Fiction;thriller;animé',
                                             'Ciencia Ficcion;Thriller;Romantica'='Science Fiction;thriller;romantique',
                                             'Ciencia Ficcion;Reality;Aventura/Accion'='Science Fiction;TV réalité;aventure/action',
                                             'Ciencia Ficcion;Reality;Drama'='Science Fiction;TV réalité;drame',
                                             'Ciencia Ficcion;Reality;Terror'='Science Fiction;TV réalité;horreur',
                                             'Ciencia Ficcion;Reality;Humor/Comedia'='Science Fiction;TV réalité;humour/comédie',
                                             'Ciencia Ficcion;Reality;Thriller'='Science Fiction;TV réalité;thriller',
                                             'Monologos;Anime;Romantica'='stand-up;animé;romantique',
                                             'Monologos;Documental;Romantica'='stand-up;documentaire;romantique',
                                             'Monologos;Documental;Thriller'='stand-up;documentaire;thriller',
                                             'Reality'='TV réalité',
                                             'Reality;Anime;Infantil'='TV réalité;animé;jeunesse et famille',
                                             'Reality;Aventura/Accion'='TV réalité;aventure/action',
                                             'Reality;Aventura/Accion;Anime'='TV réalité;aventure/action;animé',
                                             'Reality;Aventura/Accion;Documental'='TV réalité;aventure/action;documentaire',
                                             'Reality;Aventura/Accion;Drama'='TV réalité;aventure/action;drame',
                                             'Reality;Aventura/Accion;Infantil'='TV réalité;aventure/action;jeunesse et famille',
                                             'Reality;Aventura/Accion;Romantica'='TV réalité;aventure/action;romantique',
                                             'Reality;Aventura/Accion;Thriller'='TV réalité;aventure/action;thriller',
                                             'Reality;Documental;Drama'='TV réalité;documentaire;drame',
                                             'Reality;Drama;Infantil'='TV réalité;drame;jeunesse et famille',
                                             'Reality;Drama;Romantica'='TV réalité;drame;romantique',
                                             'Reality;Drama;Thriller'='TV réalité;drame;thriller',
                                             'Reality;Terror;Aventura/Accion'='TV réalité;horreur;aventure/action',
                                             'Reality;Terror;Documental'='TV réalité;horreur;documentaire',
                                             'Reality;Terror;Drama'='TV réalité;horreur;drame',
                                             'Reality;Terror;Infantil'='TV réalité;horreur;jeunesse et famille',
                                             'Reality;Terror;Romantica'='TV réalité;horreur;romantique',
                                             'Reality;Humor/Comedia;Aventura/Accion'='TV réalité;humour/comédie;aventure/action',
                                             'Reality;Humor/Comedia;Documental'='TV réalité;humour/comédie;documentaire',
                                             'Reality;Humor/Comedia;Drama'='TV réalité;humour/comédie;drame',
                                             'Reality;Humor/Comedia;Terror'='TV réalité;humour/comédie;horreur',
                                             'Reality;Humor/Comedia;Infantil'='TV réalité;humour/comédie;jeunesse et famille',
                                             'Reality;Humor/Comedia;Romantica'='TV réalité;humour/comédie;romantique',
                                             'Anime'='animé',
                                             'Aventura/Accion'='aventure/action',
                                             'Aventura/Accion;Biopic'='aventure/action;biopic (biographie)',
                                             'Aventura/Accion;Documental;Anime'='aventure/action;documentaire;animé',
                                             'Aventura/Accion;Documental;Drama'='aventure/action;documentaire;drame',
                                             'Aventura/Accion;Documental;Thriller'='aventure/action;documentaire;thriller',
                                             'Aventura/Accion;Drama;Infantil'='aventure/action;drame;jeunesse et famille',
                                             'Aventura/Accion;Drama;Romantica'='aventure/action;drame;romantique',
                                             'Aventura/Accion;Drama;Thriller'='aventure/action;drame;thriller',
                                             'Aventura/Accion;Historica;Anime'='aventure/action;historique;animé',
                                             'Aventura/Accion;Historica;Biopic'='aventure/action;historique;biopic (biographie)',
                                             'Aventura/Accion;Historica;Drama'='aventure/action;historique;drame',
                                             'Aventura/Accion;Historica;Romantica'='aventure/action;historique;romantique',
                                             'Aventura/Accion;Historica;Thriller'='aventure/action;historique;thriller',
                                             'Aventura/Accion;Thriller'='aventure/action;thriller',
                                             'Aventura/Accion;Thriller;Romantica'='aventure/action;thriller;romantique',
                                             'Biopic'='biopic (biographie)',
                                             'Documental;Anime;Biopic'='documentaire;animé;biopic (biographie)',
                                             'Documental;Anime;Romantica'='documentaire;animé;romantique',
                                             'Documental;Drama;Biopic'='documentaire;drame;biopic (biographie)',
                                             'Documental;Drama;Romantica'='documentaire;drame;romantique',
                                             'Drama;Biopic;Romantica'='drame;biopic (biographie);romantique',
                                             'Drama;Romantica'='drame;romantique',
                                             'Drama;Thriller'='drame;thriller',
                                             'Drama;Thriller;Anime'='drame;thriller;animé',
                                             'Drama;Thriller;Infantil'='drame;thriller;jeunesse et famille',
                                             'Historica;Drama;Romantica'='historique;drame;romantique',
                                             'Historica;Thriller'='historique;thriller',
                                             'Terror'='horreur',
                                             'Terror;Aventura/Accion;Anime'='horreur;aventure/action;animé',
                                             'Terror;Aventura/Accion;Documental'='horreur;aventure/action;documentaire',
                                             'Terror;Aventura/Accion;Drama'='horreur;aventure/action;drame',
                                             'Terror;Aventura/Accion;Historica'='horreur;aventure/action;historique',
                                             'Terror;Aventura/Accion;Infantil'='horreur;aventure/action;jeunesse et famille',
                                             'Terror;Aventura/Accion;Thriller'='horreur;aventure/action;thriller',
                                             'Terror;Documental;Drama'='horreur;documentaire;drame',
                                             'Terror;Drama;Romantica'='horreur;drame;romantique',
                                             'Terror;Drama;Thriller'='horreur;drame;thriller',
                                             'Terror;Infantil;Romantica'='horreur;jeunesse et famille;romantique',
                                             'Terror;Thriller;Anime'='horreur;thriller;animé',
                                             'Humor/Comedia'='humour/comédie',
                                             'Humor/Comedia;Anime;Otra'='humour/comédie;animé;autre (précisez)',
                                             'Humor/Comedia;Anime;Infantil'='humour/comédie;animé;jeunesse et famille',
                                             'Humor/Comedia;Anime;Romantica'='humour/comédie;animé;romantique',
                                             'Humor/Comedia;Aventura/Accion'='humour/comédie;aventure/action',
                                             'Humor/Comedia;Aventura/Accion;Anime'='humour/comédie;aventure/action;animé',
                                             'Humor/Comedia;Aventura/Accion;Documental'='humour/comédie;aventure/action;documentaire',
                                             'Humor/Comedia;Aventura/Accion;Drama'='humour/comédie;aventure/action;drame',
                                             'Humor/Comedia;Aventura/Accion;Historica'='humour/comédie;aventure/action;historique',
                                             'Humor/Comedia;Aventura/Accion;Infantil'='humour/comédie;aventure/action;jeunesse et famille',
                                             'Humor/Comedia;Aventura/Accion;Romantica'='humour/comédie;aventure/action;romantique',
                                             'Humor/Comedia;Aventura/Accion;Thriller'='humour/comédie;aventure/action;thriller',
                                             'Humor/Comedia;Biopic;Romantica'='humour/comédie;biopic (biographie);romantique',
                                             'Humor/Comedia;Documental;Anime'='humour/comédie;documentaire;animé',
                                             'Humor/Comedia;Documental;Infantil'='humour/comédie;documentaire;jeunesse et famille',
                                             'Humor/Comedia;Documental;Romantica'='humour/comédie;documentaire;romantique',
                                             'Humor/Comedia;Drama;Romantica'='humour/comédie;drame;romantique',
                                             'Humor/Comedia;Drama;Thriller'='humour/comédie;drame;thriller',
                                             'Humor/Comedia;Historica;Biopic'='humour/comédie;historique;biopic (biographie)',
                                             'Humor/Comedia;Historica;Drama'='humour/comédie;historique;drame',
                                             'Humor/Comedia;Historica;Infantil'='humour/comédie;historique;jeunesse et famille',
                                             'Humor/Comedia;Historica;Thriller'='humour/comédie;historique;thriller',
                                             'Humor/Comedia;Terror;Anime'='humour/comédie;horreur;animé',
                                             'Humor/Comedia;Terror;Aventura/Accion'='humour/comédie;horreur;aventure/action',
                                             'Humor/Comedia;Terror;Documental'='humour/comédie;horreur;documentaire',
                                             'Humor/Comedia;Terror;Infantil'='humour/comédie;horreur;jeunesse et famille',
                                             'Humor/Comedia;Terror;Romantica'='humour/comédie;horreur;romantique',
                                             'Humor/Comedia;Terror;Thriller'='humour/comédie;horreur;thriller',
                                             'Humor/Comedia;Infantil;Romantica'='humour/comédie;jeunesse et famille;romantique',
                                             'Humor/Comedia;Monologos;Anime'='humour/comédie;stand-up;animé',
                                             'Humor/Comedia;Monologos;Aventura/Accion'='humour/comédie;stand-up;aventure/action',
                                             'Humor/Comedia;Monologos;Documental'='humour/comédie;stand-up;documentaire',
                                             'Humor/Comedia;Monologos;Thriller'='humour/comédie;stand-up;thriller',
                                             'Humor/Comedia;Thriller;Biopic'='humour/comédie;thriller;biopic (biographie)',
                                             'Romantica'='romantique',
                                             'Ciencia Ficcion'='Science Fiction',
                                             'Ciencia Ficcion;Aventura/Accion'='Science Fiction;aventure/action',
                                             'Ciencia Ficcion;Aventura/Accion;Anime'='Science Fiction;aventure/action;animé',
                                             'Ciencia Ficcion;Aventura/Accion;Documental'='Science Fiction;aventure/action;documentaire',
                                             'Ciencia Ficcion;Aventura/Accion;Drama'='Science Fiction;aventure/action;drame',
                                             'Ciencia Ficcion;Aventura/Accion;Romantica'='Science Fiction;aventure/action;romantique',
                                             'Ciencia Ficcion;Aventura/Accion;Thriller'='Science Fiction;aventure/action;thriller',
                                             'Ciencia Ficcion;Biopic;Infantil'='Science Fiction;biopic (biographie);jeunesse et famille',
                                             'Ciencia Ficcion;Documental;Anime'='Science Fiction;documentaire;animé',
                                             'Ciencia Ficcion;Drama;Thriller'='Science Fiction;drame;thriller',
                                             'Ciencia Ficcion;Historica;Thriller'='Science Fiction;historique;thriller',
                                             'Ciencia Ficcion;Terror'='Science Fiction;horreur',
                                             'Ciencia Ficcion;Terror;Anime'='Science Fiction;horreur;animé',
                                             'Ciencia Ficcion;Terror;Aventura/Accion'='Science Fiction;horreur;aventure/action',
                                             'Ciencia Ficcion;Terror;Documental'='Science Fiction;horreur;documentaire',
                                             'Ciencia Ficcion;Terror;Romantica'='Science Fiction;horreur;romantique',
                                             'Ciencia Ficcion;Terror;Thriller'='Science Fiction;horreur;thriller',
                                             'Ciencia Ficcion;Humor/Comedia'='Science Fiction;humour/comédie',
                                             'Ciencia Ficcion;Humor/Comedia;Anime'='Science Fiction;humour/comédie;animé',
                                             'Ciencia Ficcion;Humor/Comedia;Aventura/Accion'='Science Fiction;humour/comédie;aventure/action',
                                             'Ciencia Ficcion;Humor/Comedia;Documental'='Science Fiction;humour/comédie;documentaire',
                                             'Ciencia Ficcion;Humor/Comedia;Historica'='Science Fiction;humour/comédie;historique',
                                             'Ciencia Ficcion;Humor/Comedia;Terror'='Science Fiction;humour/comédie;horreur',
                                             'Ciencia Ficcion;Humor/Comedia;Romantica'='Science Fiction;humour/comédie;romantique',
                                             'Ciencia Ficcion;Humor/Comedia;Monologos'='Science Fiction;humour/comédie;stand-up',
                                             'Ciencia Ficcion;Humor/Comedia;Thriller'='Science Fiction;humour/comédie;thriller',
                                             'Ciencia Ficcion;Thriller;Anime'='Science Fiction;thriller;animé',
                                             'Ciencia Ficcion;Thriller;Romantica'='Science Fiction;thriller;romantique',
                                             'Ciencia Ficcion;Reality;Aventura/Accion'='Science Fiction;TV réalité;aventure/action',
                                             'Ciencia Ficcion;Reality;Drama'='Science Fiction;TV réalité;drame',
                                             'Ciencia Ficcion;Reality;Terror'='Science Fiction;TV réalité;horreur',
                                             'Ciencia Ficcion;Reality;Humor/Comedia'='Science Fiction;TV réalité;humour/comédie',
                                             'Ciencia Ficcion;Reality;Thriller'='Science Fiction;TV réalité;thriller',
                                             'Monologos;Anime;Romantica'='stand-up;animé;romantique',
                                             'Monologos;Documental;Romantica'='stand-up;documentaire;romantique',
                                             'Monologos;Documental;Thriller'='stand-up;documentaire;thriller',
                                             'Reality'='TV réalité',
                                             'Reality;Anime;Infantil'='TV réalité;animé;jeunesse et famille',
                                             'Reality;Aventura/Accion'='TV réalité;aventure/action',
                                             'Reality;Aventura/Accion;Anime'='TV réalité;aventure/action;animé',
                                             'Reality;Aventura/Accion;Documental'='TV réalité;aventure/action;documentaire',
                                             'Reality;Aventura/Accion;Drama'='TV réalité;aventure/action;drame',
                                             'Reality;Aventura/Accion;Infantil'='TV réalité;aventure/action;jeunesse et famille',
                                             'Reality;Aventura/Accion;Romantica'='TV réalité;aventure/action;romantique',
                                             'Reality;Aventura/Accion;Thriller'='TV réalité;aventure/action;thriller',
                                             'Reality;Documental;Drama'='TV réalité;documentaire;drame',
                                             'Reality;Drama;Infantil'='TV réalité;drame;jeunesse et famille',
                                             'Reality;Drama;Romantica'='TV réalité;drame;romantique',
                                             'Reality;Drama;Thriller'='TV réalité;drame;thriller',
                                             'Reality;Terror;Aventura/Accion'='TV réalité;horreur;aventure/action',
                                             'Reality;Terror;Documental'='TV réalité;horreur;documentaire',
                                             'Reality;Terror;Drama'='TV réalité;horreur;drame',
                                             'Reality;Terror;Infantil'='TV réalité;horreur;jeunesse et famille',
                                             'Reality;Terror;Romantica'='TV réalité;horreur;romantique',
                                             'Reality;Humor/Comedia;Aventura/Accion'='TV réalité;humour/comédie;aventure/action',
                                             'Reality;Humor/Comedia;Documental'='TV réalité;humour/comédie;documentaire',
                                             'Reality;Humor/Comedia;Drama'='TV réalité;humour/comédie;drame',
                                             'Reality;Humor/Comedia;Terror'='TV réalité;humour/comédie;horreur',
                                             'Reality;Humor/Comedia;Infantil'='TV réalité;humour/comédie;jeunesse et famille',
                                             'Reality;Humor/Comedia;Romantica'='TV réalité;humour/comédie;romantique')

datos[datos %>% select(FrecuenciaNetflix,Actitud1:Barreras9) %>% colnames()] <- 
  datos %>% select(FrecuenciaNetflix,Actitud1:Barreras9) %>% map_df(.,parse_number)

datos[datos %>% select(RecenciaNetflix:BenefEsp13,ControlPerc1:ControlPerc2) %>% colnames()] <-
  datos %>% select(RecenciaNetflix:BenefEsp13,ControlPerc1:ControlPerc2) %>% map_df(.,factor.ordinal)

datos$Sexo <- fct_recode(datos$Sexo,
                         'Otro'='Autre (précisez)',
                         'Hombre'='Un homme',
                         'Mujer'='Une femme')

# SELECCIONAMOS VARIABLES A SALVAR EN LA BBDD DEPURADA

datos <- datos %>% select(ID,Plataformas,FrecuenciaInternet,SeriesFavoritas,FrecuenciaNetflix:Sexo,Edad,TiempoResp)

# GUARDAMOS NUEVA BBDD

readr::write_csv(datos,'Netflix2020Depurado.csv')
