\documentclass{article}
\usepackage{graphicx}
\usepackage{float}
\usepackage{Sweave}
\usepackage{geometry}
\usepackage[T1]{fontenc}
\geometry{
  a4paper,
  total={170mm,257mm},
  left=20mm,
  top=20mm}

\title{Informe}
\author{Max Comerma i Martos}
\date{\today}
\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle

<<setup, include=FALSE, echo=FALSE>>=
library(tidyverse)
library(xtable)
library(dplyr)
data <- read_csv("data.csv")
data <- data %>%
  mutate(AGE.A = case_when(
    EDAD >= 15 & EDAD <= 20 ~ "15-20 años",
    EDAD > 20 & EDAD <= 40 ~ "20-40 años",
    EDAD > 40 & EDAD <= 60 ~ "40-60 años",
    EDAD > 60 ~ "Más de 60 años"))
@

\section{Tablas Resumen}
\subsection{Demográficas}

<<tabla-resumen, echo=FALSE, message=FALSE, warning=FALSE, results=tex>>=
tabla_resumen <- data %>%
  summarize(
    Edad_Media = mean(EDAD),
    Hombres = mean(GENERO == "1") * 100,
    Menos_Secundaria = mean(EDU == "1") * 100,
    Universitarios = mean(EDU == "5") * 100,
    Comodamente = mean(SENSA.SUELDO == "1") * 100,
    Sobrellevando = mean(SENSA.SUELDO == "2") * 100)

print(xtable(tabla_resumen, 
             caption = "Tabla Resumen", 
             align = c("r", "r", "r", "r", "r", "r","r")),
      include.rownames = FALSE, caption.placement = "top")

cat("En esta tabla se observa que hay más hombres que mujeres,",
  "que la edad media es de", round(tabla_resumen$Edad_Media, 1), "años,",
  "que el", round(tabla_resumen$Menos_Secundaria, 1), "\\% de las personas encuestadas",
  "no acabaron la secundaria y que un", round(tabla_resumen$Universitarios, 1), "\\% son universitarios.",
  "Además, aproximadamente el", round(tabla_resumen$Comodamente + tabla_resumen$Sobrellevando, 1), "\\% de los encuestados vive sin dificultades económicas.")
@
\subsection{Minorías}

<<freq-minoria, echo=FALSE, message=FALSE, warning=FALSE, results=tex>>=
freq_minoria <- as.data.frame(table(data$MINORIA))
colnames(freq_minoria) <- c("Minoria", "Frecuencia")
freq_minoria$Minoria <- factor(freq_minoria$Minoria, levels = c(1, 2), labels = c("Sí", "No"))
print(xtable(freq_minoria, 
             caption = "Frecuencias Minoria", 
             align = c("r", "r", "r")),include.rownames = FALSE,caption.placement = "top")
cat("Observamos que apenas hay minorías étnicas en la muestra, no van a ser tomadas en cuenta para nuestros futuros análisis.")
@
\subsection{Diarios y TV}

<<freqcombinado, echo=FALSE, message=FALSE, warning=FALSE, results=tex>>=
FD <- as.data.frame(table(data$DIARIO))
FT <- as.data.frame(table(data$TV))
colnames(FD) <- c("Categoría", "Frecuencia Diario")
colnames(FT) <- c("Categoría", "Frecuencia TV")
CT <- merge(FD, FT, by = "Categoría", all = TRUE)
Etiquetas <- c("0" = "Nada","1" = "Menos de 0,5 horas", "2" = "0,5 horas a 1 hora", "3" = "Más de 1 hora, hasta 1,5 horas", "4" = "Más de 1,5 horas, hasta 2 horas","5" = "Más de 2 horas, hasta 2,5 horas","6" = "Más de 2,5 horas, hasta 3 horas","7" = "Más de 3 horas")
CT$Categoría <- factor(CT$Categoría, levels = names(Etiquetas))
CT$Categoría <- as.character(CT$Categoría)
CT$Categoría <- Etiquetas[CT$Categoría]
print(xtable(CT,caption = "Frecuencia Diario y TV por Categoría", 
             align = c("l", "r", "r", "r")), include.rownames = FALSE,caption.placement = "top")
cat("Al comparar el tiempo dedicado a informarse mediante el diario y la televisión, las personas se informan de política ligeramente más tiempo leyendo el diario y para ambas preguntas es poco frecuente dedicarle más de 1 hora, tampoco tendremos en cuenta estas variables para futuros análisis.")
@
\section{Gráficos}

\begin{figure}[H]
\begin{minipage}[t]{0.5\linewidth}
\centering
<<echo=FALSE, fig=TRUE, fig.cap="Distribución por Edad", fig.width=8, fig.height=6>>=
ggplot(data, aes(x = AGE.A, fill = AGE.A)) +
  geom_bar() +
  scale_fill_manual(values = c("15-20 años" = "#ADD8E6","20-40 años" = "#87CEFA", "40-60 años" = "#4682B4","Más de 60 años" = "#000080")) +
  labs(title = "Distribución por Edad", x = "", y = "Frecuencia") +
  theme(legend.position = "none")
@
\caption{Distribución por Edad}
\end{minipage}%
\begin{minipage}[t]{0.5\linewidth}
\centering
<<echo=FALSE, fig=TRUE, fig.cap="Distribución por Inseguridad en la Calle", fig.width=8, fig.height=6>>=

data$SEGURO.NOCHE <- factor(data$SEGURO.NOCHE, 
                            levels = c(1, 2, 3, 4),
                            labels = c("Muy seguro", "Seguro", "Inseguro", "Muy inseguro"))
  ggplot(data, aes(x = SEGURO.NOCHE, fill = as.factor(SEGURO.NOCHE))) +
    geom_bar() +
    scale_fill_manual(values = c("Muy seguro" = "green","Seguro" = "lightgreen"
                                 , "Inseguro" = "lightcoral", "Muy inseguro" = "red")) + 

    labs(title = "Sensación de Seguridad", x = "", y = "Frecuencia") +
    theme(legend.position = "none")
@
\caption{Distribución por Nivel Educativo}
\end{minipage}


\begin{minipage}[t]{0.5\linewidth}
\centering
<<echo=FALSE, fig=TRUE, fig.cap="Distribución por Nivel de Ingresos", fig.width=8, fig.height=6>>=
ggplot(data, aes(x = factor(SENSA.SUELDO, levels = c("4", "3", "2", "1")), fill = as.factor(SENSA.SUELDO))) +
  geom_bar() +
  scale_x_discrete(labels = c(
    "1" = "Vivo cómodamente",
    "2" = "Sobrellevo",
    "3" = "Difícil",
    "4" = "Muy difícil")) +
  scale_fill_manual(values = c(
    "1" = "green","2" = "lightgreen","3" = "lightsalmon","4" = "lightcoral")) +
  labs(title = "Distribución por Nivel de Ingresos", x = "", y = "Frecuencia") +
  theme(legend.position = "none")
@
\caption{Distribución por Nivel de Ingresos}
\end{minipage}
\begin{minipage}[t]{0.5\linewidth}
\vspace{-5cm}
\centering
\begin{itemize}
  \item \textbf{Distribución por Edad:} La mayoría de los encuestados tienen entre 20 y 40 años.
  \item \textbf{Distribución por Seguridad en la Calle:} Se observa que mayoritariamente hay percepción de seguridad al andar por la calle de noche.
  \item \textbf{Distribución por Nivel de Ingresos:} Como se comentaba anteriormente, la mayoría de las personas no presenta dificultades económicas.
\end{itemize}
\end{minipage}
\end{figure}

<<setup, include=FALSE, echo=FALSE>>=
library(tidyverse)
library(xtable)
library(dplyr)

data <- data %>%
  mutate(AGE.A = case_when(
    EDAD >= 15 & EDAD <= 20 ~ "15-20 años",
    EDAD > 20 & EDAD <= 40 ~ "20-40 años",
    EDAD > 40 & EDAD <= 60 ~ "40-60 años",
    EDAD > 60 ~ "Más de 60 años"))


data <- data %>%
  mutate(INM.LARGO.A = case_when(INM.LARGO >= 0 & INM.LARGO <= 2 ~ "Muy Malo",
    INM.LARGO > 2 & INM.LARGO <= 4 ~ "Malo",
    INM.LARGO > 4 & INM.LARGO <= 6 ~ "Medio",
    INM.LARGO > 6 & INM.LARGO <= 8 ~ "Bueno",
    INM.LARGO > 8 & INM.LARGO <= 10 ~ "Muy Bueno"
  ))


data$ROBO5.A <- factor(data$ROBO5.A, levels = c(1, 2), labels = c("Sí", "No"))
data$GENERO <- factor(data$GENERO, levels = c(1, 2), labels = c("Hombre", "Mujer"))
data$SEGURO.NOCHE <- factor(data$SEGURO.NOCHE, levels = c(1, 2, 3, 4), labels = c("Muy seguro", "Seguro", "Inseguro", "Muy inseguro"))
data$INM.RICOS <- factor(data$INM.RICOS, levels = c(1, 2, 3, 4), labels = c("Permitir muchos", "Permitir algunos", "Permitir unos pocos", "No permitir ninguno"))
data$INM.POBRES <- factor(data$INM.POBRES, levels = c(1, 2, 3, 4), labels = c("Permitir muchos", "Permitir algunos", "Permitir unos pocos", "No permitir ninguno"))
data$D.ECO <- factor(data$D.ECO, levels = c(1, 2, 3, 4, 5), labels = c("Totalmente de acuerdo", "De acuerdo", "Ni de acuerdo ni en desacuerdo", "En desacuerdo", "Totalmente en desacuerdo"))
data$CRIMEN <- factor(data$CRIMEN, levels = c(1, 2, 3, 4, 5), labels = c("Totalmente de acuerdo", "De acuerdo", "Ni de acuerdo ni en desacuerdo", "En desacuerdo", "Totalmente en desacuerdo"))
data$TENSION <- factor(data$TENSION, levels = c(1, 2, 3, 4, 5), labels = c("Totalmente de acuerdo", "De acuerdo", "Ni de acuerdo ni en desacuerdo", "En desacuerdo", "Totalmente en desacuerdo"))
data$AGE.A <- factor(data$AGE.A, levels = c("15-20 años", "20-40 años", "40-60 años", "Más de 60 años"))
data$EDU <- factor(data$EDU, levels = c(1, 2, 3, 4, 5), labels = c("Menos que secundaria", "Secundaria inferior", "Secundaria superior", "Postsecundaria", "Universitaria"))
data$SENSA.SUELDO <- factor(data$SENSA.SUELDO, levels = c(1, 2, 3, 4), labels = c("Cómodamente", "Sobrellevo", "Difícil", "Muy Difícil"))

@
\section{Gráficos Comparativos}


\newcommand{\imgpath}{} %CAMBIAR POR EL Working Directory

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath CRIMENEDAD.jpg}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath CRIMENSUELDO.jpg}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath DECOSUELDO.jpg}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath EDADRICOS.jpg}
\end{figure}


\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath INMPOBRESSUELDO.jpg}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath NOCHESUELDO.jpg}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath NOCHES.jpg}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\imgpath POBRESEDAD.jpg}

\end{figure}

Estos gráficos nos permiten comparar, las diferentes variable demográficas con las variables de interés. Destacamos que, por encima de las demás variables, la percepción del sueldo es la que presenta más diferencia entre los grupos, mientras que el género, parece no tener mucha influencia. En general, no se aprecian a primera vista demasiadas diferencias entre grupos.

En la variable CRIMEN, se observa que las personas más mayores, están más a favor que las jóvenes a deportar a los inmigrantes si cometen algún crimen. Con esta misma variable, se observa que las personas con más dificultades económicas, también están más a favor de la afirmación. Como era de esperar, los hombres sienten un poco más de seguridad nocturna que las mujeres.

Para finalizar, recalcar que es necesario hacer un análisis más profundo para observar si las relaciones son significativas y con qué intensidad se dan. 


\end{document}
