---
title: "Dashboard Interactivo"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup1, include=FALSE}
library(shiny)
library(ggplot2)
library(dplyr)
library(flexdashboard)

data <- read.csv("data.csv")

data <- data %>%
  mutate(AGE.A = case_when(
    EDAD >= 15 & EDAD <= 20 ~ "15-20 años",
    EDAD > 20 & EDAD <= 40 ~ "20-40 años",
    EDAD > 40 & EDAD <= 60 ~ "40-60 años",
    EDAD > 60 ~ "Más de 60 años"))


data <- data %>%
  mutate(INM.LARGO.A = case_when(INM.LARGO >= 0 & INM.LARGO <= 2 ~ "Muy Malo",
    INM.LARGO > 2 & INM.LARGO <= 4 ~ "Malo",
    INM.LARGO > 4 & INM.LARGO <= 6 ~ "Medio",
    INM.LARGO > 6 & INM.LARGO <= 8 ~ "Bueno",
    INM.LARGO > 8 & INM.LARGO <= 10 ~ "Muy Bueno"
  ))


data$ROBO5.A <- factor(data$ROBO5.A, levels = c(1, 2), labels = c("Sí", "No"))
data$GENERO <- factor(data$GENERO, levels = c(1, 2), labels = c("Hombre", "Mujer"))
data$SEGURO.NOCHE <- factor(data$SEGURO.NOCHE, levels = c(1, 2, 3, 4), labels = c("Muy seguro", "Seguro", "Inseguro", "Muy inseguro"))
data$INM.RICOS <- factor(data$INM.RICOS, levels = c(1, 2, 3, 4), labels = c("Permitir muchos", "Permitir algunos", "Permitir unos pocos", "No permitir ninguno"))
data$INM.POBRES <- factor(data$INM.POBRES, levels = c(1, 2, 3, 4), labels = c("Permitir muchos", "Permitir algunos", "Permitir unos pocos", "No permitir ninguno"))
data$D.ECO <- factor(data$D.ECO, levels = c(1, 2, 3, 4, 5), labels = c("Totalmente de acuerdo", "De acuerdo", "Ni de acuerdo ni en desacuerdo", "En desacuerdo", "Totalmente en desacuerdo"))
data$CRIMEN <- factor(data$CRIMEN, levels = c(1, 2, 3, 4, 5), labels = c("Totalmente de acuerdo", "De acuerdo", "Ni de acuerdo ni en desacuerdo", "En desacuerdo", "Totalmente en desacuerdo"))
data$TENSION <- factor(data$TENSION, levels = c(1, 2, 3, 4, 5), labels = c("Totalmente de acuerdo", "De acuerdo", "Ni de acuerdo ni en desacuerdo", "En desacuerdo", "Totalmente en desacuerdo"))
data$AGE.A <- factor(data$AGE.A, levels = c("15-20 años", "20-40 años", "40-60 años", "Más de 60 años"))
data$EDU <- factor(data$EDU, levels = c(1, 2, 3, 4, 5), labels = c("Menos que secundaria", "Secundaria inferior", "Secundaria superior", "Postsecundaria", "Universitaria"))
data$SENSA.SUELDO <- factor(data$SENSA.SUELDO, levels = c(1, 2, 3, 4), labels = c("Cómodamente", "Sobrellevo", "Difícil", "Muy Difícil"))

```

```{r ui}
ui <- fluidPage(titlePanel("Dashboard Interactivo"),sidebarLayout(sidebarPanel(
      width = 3,
      selectInput("section", "Selecciona Sección:", choices = list("Principal" = "Principal","Variables Demográficas" = "demograficas","Seguridad y Robos" = "seguridad","Inmigración" = "inmigracion","Análisis de Interacción" = "interaccion")),
      conditionalPanel(condition = "input.section === 'interaccion'",selectInput("desglose", "Desglose:", choices = c("Género" = "GENERO","Edad" = "AGE.A","Educación" = "EDU","Sensación de Sueldo" = "SENSA.SUELDO")),selectInput("variable", "Variable:", 
                    choices = c("SEGURO.NOCHE", "INM.RICOS", "INM.POBRES", "D.ECO", "CRIMEN", "INM.LARGO.A", "TENSION")))),
    mainPanel(uiOutput("content"),  conditionalPanel(condition = "input.section === 'interaccion'", plotOutput("barPlot")))))
```

```{r server}

server <- function(input, output) {

  output$content <- renderUI({
    switch(input$section, Principal = fluidRow(column(12, h1("Dashboard Interactivo de los Resultados del ESS1")),
             column(12, p("En este dashboard, vas a encontrar diferentes gráficos obtenidos de una encuesta relacionada especialmente con la inmigración, primero se presentan los gráficos sobre las variables demográficas, después sobre la seguridad, posteriormente sobre la inmigración y por último se encuentran 4 secciones que comparan por cada variable demográfica las diferentes respuestas sobre inmigración."))),
           demograficas = fluidRow(column(6, plotOutput("plot_gender")),column(6, plotOutput("plot_age")),
             column(6, plotOutput("plot_education")),
             column(6, plotOutput("plot_income"))),
           seguridad = fluidRow(
             column(6, plotOutput("plot_security")),
             column(6, plotOutput("plot_robbery"))),
           inmigracion = fluidRow(
             column(6, plotOutput("plot_inm_ricos")),
             column(6, plotOutput("plot_inm_pobres")),
             column(6, plotOutput("plot_inm_largo")),
             column(6, plotOutput("plot_d_eco")),
             column(6, plotOutput("plot_crimen")),
             column(6, plotOutput("plot_tension"))))})

calculate_proportions <- function(data, var, desglose) {
  data %>%
    group_by_at(vars(desglose, var)) %>%
    summarise(n = n(), .groups = 'drop') %>%
    group_by_at(desglose) %>%
    mutate(proporcion = n / sum(n)) %>%
    mutate(value = as.character(.data[[var]])) %>%
    mutate_at(vars(desglose), ~recode(.x,`1` = "Hombre",`2` = "Mujer")) %>%
    select(!!desglose, value, n, proporcion)}

output$barPlot <- renderPlot({
  req(input$desglose, input$variable) 
  desglose <- input$desglose
  variable <- input$variable
  proporciones_data <- calculate_proportions(data, variable, desglose)
  
  ggplot(proporciones_data, aes(x = factor(value, levels = unique(value)), y = proporcion, fill = !!sym(desglose))) +
    geom_bar(stat = "identity", position = "dodge") +
    labs(title = paste("Proporciones de", variable, "por", desglose),
         x = variable,
         y = "Proporción") +
    scale_fill_manual(values = c("Hombre" = "lightblue", 
                                  "Mujer" = "lightpink", 
                                  "15-20 años" = "#ADD8E6", 
                                  "20-40 años" = "#87CEFA", 
                                  "40-60 años" = "#4682B4", 
                                  "Más de 60 años" = "#000080", 
                                  "Menos que secundaria" = "#f7fbff", 
                                  "Secundaria inferior" = "#c6dbef", 
                                  "Secundaria superior" = "#6baed6", 
                                  "Postsecundaria" = "#2171b5", 
                                  "Universitaria" = "#08306b", 
                                  "Cómodamente" = "green", 
                                  "Sobrellevo" = "lightgreen", 
                                  "Difícil" = "lightcoral", 
                                  "Muy Difícil" = "red"), name = desglose) +
    theme(legend.position = "bottom")
})

output$plot_gender <- renderPlot({
  ggplot(data, aes(x = as.factor(GENERO), fill = as.factor(GENERO))) +
    geom_bar() +
    scale_fill_manual(values = c("Hombre" = "lightblue", "Mujer" = "lightpink")) +
    labs(title = "Distribución por Género", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_age <- renderPlot({
  ggplot(data, aes(x = AGE.A, fill = AGE.A)) +
    geom_bar() +
    scale_fill_manual(values = c("15-20 años" = "#ADD8E6", 
                                 "20-40 años" = "#87CEFA", 
                                 "40-60 años" = "#4682B4", 
                                 "Más de 60 años" = "#000080")) +
    labs(title = "Distribución por Edad", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_education <- renderPlot({
  ggplot(data, aes(x = as.factor(EDU), fill = as.factor(EDU))) +
    geom_bar() +
scale_fill_manual(values = c("Menos que secundaria" = "#f7fbff", 
                             "Secundaria inferior" = "#c6dbef", 
                             "Secundaria superior" = "#6baed6", 
                             "Postsecundaria" = "#2171b5", 
                             "Universitaria" = "#08306b"))+
    labs(title = "Distribución por Nivel Educativo", x = "", y = "Frecuencia") +
    theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1))})

output$plot_income <- renderPlot({
  ggplot(data, aes(x = SENSA.SUELDO, fill = as.factor(SENSA.SUELDO))) +
    geom_bar() +
      scale_fill_manual(values = c(
        "Cómodamente" = "green", 
        "Sobrellevo" = "lightgreen", 
        "Difícil" = "lightcoral", 
        "Muy Difícil" = "red")) +
    labs(title = "Distribución por Nivel de Ingresos", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_security <- renderPlot({
  ggplot(data, aes(x = SEGURO.NOCHE, fill = as.factor(SEGURO.NOCHE))) +
    geom_bar() +
    scale_fill_manual(values = c("Muy seguro" = "green", 
                                 "Seguro" = "lightgreen", 
                                 "Inseguro" = "lightcoral", 
                                 "Muy inseguro" = "red")) +
    labs(title = "Sensación de Seguridad", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_robbery <- renderPlot({
  ggplot(data, aes(x = as.factor(ROBO5.A), fill = as.factor(ROBO5.A))) +
    geom_bar() +
    labs(title = "Robo o Agresión en los últimos 5 años", x = "", y = "Frecuencia") +
    scale_fill_manual(values = c("Sí" = "green", "No" = "red")) +
    theme(legend.position = "none")})

output$plot_inm_ricos <- renderPlot({
  ggplot(data, aes(x = INM.RICOS, fill = as.factor(INM.RICOS))) +
    geom_bar() +
    scale_fill_manual(values = c("Permitir muchos" = "green",   
                                 "Permitir algunos" = "lightgreen",    
                                 "Permitir unos pocos" = "lightcoral",    
                                 "No permitir ninguno" = "red")) +
    labs(title = "Percepción sobre la Inmigración de Ciudadanos Ricos", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_inm_pobres <- renderPlot({
  ggplot(data, aes(x = INM.POBRES, fill = as.factor(INM.POBRES))) +
    geom_bar() +
    scale_fill_manual(values = c("Permitir muchos" = "green",   
                                 "Permitir algunos" = "lightgreen",    
                                 "Permitir unos pocos" = "lightcoral",    
                                 "No permitir ninguno" = "red")) +
    labs(title = "Percepción sobre la Inmigración de Ciudadanos Pobres", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_inm_largo <- renderPlot({
  ggplot(data, aes(x = factor(INM.LARGO.A, levels = c("Muy Bueno", "Bueno", "Medio", "Malo", "Muy Malo")), fill = as.factor(INM.LARGO.A))) +
    geom_bar() +
    scale_fill_manual(values = c("Muy Malo" = "red",
                                 "Malo" = "lightcoral",
                                 "Medio" = "lightblue",
                                 "Bueno" = "lightgreen",
                                 "Muy Bueno" = "green")) +
    labs(title = "Percepción del Impacto de la Inmigración a Largo Plazo", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_d_eco <- renderPlot({
  ggplot(data, aes(x = D.ECO, fill = as.factor(D.ECO))) +
    geom_bar() +
    scale_fill_manual(values = c("Totalmente de acuerdo" = "green",
                                 "De acuerdo" = "lightgreen",
                                 "Ni de acuerdo ni en desacuerdo" = "lightblue",
                                 "En desacuerdo" = "lightcoral",
                                 "Totalmente en desacuerdo" = "red")) +
    labs(title = "El Impacto Económico es Mayor en las Personas Pobres que Ricas", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_crimen <- renderPlot({
  ggplot(data, aes(x = CRIMEN, fill = as.factor(CRIMEN))) +
    geom_bar() +
    scale_fill_manual(values = c("Totalmente de acuerdo" = "green",
                                 "De acuerdo" = "lightgreen",
                                 "Ni de acuerdo ni en desacuerdo" = "lightblue",
                                 "En desacuerdo" = "lightcoral",
                                 "Totalmente en desacuerdo" = "red")) +
    labs(title = "Los Inmigrantes que Cometen algún Crimen tienen que ser Deportados", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})

output$plot_tension <- renderPlot({
  ggplot(data, aes(x = TENSION, fill = as.factor(TENSION))) +
    geom_bar() +
    scale_fill_manual(values = c("Totalmente de acuerdo" = "green",
                                 "De acuerdo" = "lightgreen",
                                 "Ni de acuerdo ni en desacuerdo" = "lightblue",
                                 "En desacuerdo" = "lightcoral",
                                 "Totalmente en desacuerdo" = "red")) +
    labs(title = "Si un País Quiere Reducir Tensiones Debería Detener la Inmigración", x = "", y = "Frecuencia") +
    theme(legend.position = "none")})}

shinyApp(ui = ui, server = server)

```




